### ISSUE TITLE
unable to retrieve the value from "DATE" in flac file

### ISSUE THREAD

**Issue by lpradopostigo** [Serial-ATA/lofty-rs#147]
### Reproducer

I tried this code:

```rust

let tagged_file = match read_from_path(path) {
            Ok(tagged_file) => tagged_file,
            Err(_) => return Err(Error::NotProcessable),
        };
let tag = tagged_file.primary_tag().unwrap();

let date = tag
            .get_string(&ItemKey::Unknown(String::from("DATE")))
            .map(|s| s.to_string());

// date is None
```

### Summary

hi, i was trying to access specific tag keys from a flac file, in this case "DATE", the key-value appears on the ouput of metaflac ` metaflac --list 01\ 953.fl
ac | grep -i date`  , also happens on other files, the files that i tested were tagged with musicbrainz picard.

### Expected behavior

be able to retrieve the value of "DATE"

**Comment by lpradopostigo** [comment]
seems like that key is the problem, because i'm able to retrieve values for ARTISTS, MUSICBRAINZ_TRACKID, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID and MUSICBRAINZ_ALBUMARTISTID

**Comment by Serial-ATA** [comment]
This is because you are using `Tag` and not `VorbisComments`. When using `read_from_path`, you will get a `TaggedFile` back, which contains the generic forms of the tags stored in the file. When `VorbisComments` gets converted to `Tag`, the format-specific keys are (for the most part) lost. What you'll need to do instead is this:

```rust
let tagged_file = match read_from_path(path) {
            Ok(tagged_file) => tagged_file,
            Err(_) => return Err(Error::NotProcessable),
        };
let tag = tagged_file.primary_tag().unwrap();

let date = tag
            .get_string(&ItemKey::RecordingDate)) // The key "DATE" maps to `ItemKey::RecordingDate`
            .map(|s| s.to_string());
```

You can see the rest of the mappings here: https://github.com/Serial-ATA/lofty-rs/blob/e14c62bf750f28f416a8285028fda5139cb80dab/src/tag/item.rs#L307-L368

**Comment by lpradopostigo** [comment]
thanks @Serial-ATA, is retrieving the date now.
