### ISSUE TITLE
Add lyrics in Accessor

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#16]
Thanks for your great work! I'm using it in my project termusic and it's great.
Basically I need support for lyrics and photo. I added in accessor and it's great. I noticed that you're working heavily in the project these days thus probably it's best that you can add it in upstream.
For photo, I'm having problems for opus file. I added a photo by push_photo, and after that, it can be displayed. However, this action destroyed the tag of opus file, and I cannot modify the tag again, with error message "cannot fill the whole frame". I check with kid3, and it told me the picture frame is not correct.

**Comment by Serial-ATA** [comment]
Thanks for checking this out! I overlooked something when I redid the pictures. I'll get that fixed.

**Comment by Serial-ATA** [comment]
Fixed in https://github.com/Serial-ATA/lofty-rs/commit/c29b0012ed1982da2150e522a8148936d550a321. As for the lyrics accessor, it'd be easy to add, but I'm not sure about adding things to `Accessor` that aren't supported by all tags to avoid confusion. `Tag::insert_text` should work just fine though.

```rust
let lyrics = include_str!("lyrics.txt");

if tag.insert_text(ItemKey::Lyrics, String::from(lyrics)) {
	...
}
```

I'll probably add such methods to the tags that support them eventually though.

**Comment by tramhao** [comment]
Picture works now! and lyric works with insert_text and get_string also! Thanks so much!
