### ISSUE TITLE
`mime_type()` returns PNG for JPG

### ISSUE THREAD

**Issue by probablykasper** [Serial-ATA/lofty-rs#465]
### Reproducer

```rs
use lofty::file::TaggedFileExt;
use lofty::read_from_path;

fn main() {
	let path = "Omri - demons.mp3";
	let tagged_file = read_from_path(path).unwrap();

	let tag = tagged_file.primary_tag().unwrap();
	let picture = tag.pictures().get(0).unwrap();
	println!("{:?}", picture.mime_type());
}
```

### Summary

I have an mp3 where the `.mime_type()` returns PNG, even though it's a JPG (Metadata viewer and Chromium both say it's JPEG).

### Assets

[example.zip](https://github.com/user-attachments/files/17081289/example.zip)

### Use case
I'm implementing thumbnail caching. When decoding the image with the `image` crate using the format supplied from lofty, I get this error:
```
Format error decoding Png: Invalid PNG signature.
```

**Comment by probablykasper** [comment]
I tested 135 files, and ran into this for 7 of them. 4 `.mp3` files and 3 `.m4a` files

**Comment by Serial-ATA** [comment]
`Picture::mime_type()` just returns whatever was specified in the MIME type field, in reality someone can write anything they want in there. For some reason, for cover in this case has `image/png`, but I can clearly see it's a jpeg in a hex editor.

You *could* pass `Picture::data()` through [`Picture::from_reader()`](https://docs.rs/lofty/latest/lofty/picture/struct.Picture.html#method.from_reader), which will tell you for sure if it's a PNG or JPEG, since it reads the actual image data. The issue is it *only* works for PNG and JPEG.

I don't think anything can really be done about this in Lofty.

**Comment by probablykasper** [comment]
Ah, that makes sense. I interpreted the documentation as it being determined from the image data
> 	/// The `mime_type` is determined from the `data`, and
>	/// is immutable.

**Comment by Serial-ATA** [comment]
Oh wow. No idea why I worded it like that. Thanks for pointing that out.
